-- Clear existing data
DELETE FROM menu_items;
DELETE FROM categories;

-- Update Store Settings to ETB
UPDATE store_settings 
SET value = jsonb_set(value, '{currency}', '"ETB"')
WHERE key = 'general';

INSERT INTO categories (id, name, image_url) VALUES 
('shooters', 'Shooters', null),
('long-cocktails', 'Long Cocktails', null),
('special-menu', 'Special Menu', null),
('salads', 'Salads', null),
('soups', 'Soups', null),
('pasta', 'Pasta', null),
('rice-dishes', 'Rice Dishes', null),
('beef-dishes', 'Beef Dishes', null),
('chicken-dishes', 'Chicken Dishes', null),
('lamb-dishes', 'Lamb Dishes', null),
('fish-dishes', 'Fish Dishes', null),
('sandwiches', 'Sandwiches', null),
('burgers', 'Burgers', null),
('pizza', 'Pizza', null),
('traditional-food', 'Traditional Food', null),
('desserts', 'Desserts', null),
('day-special-menu', 'Day Special Menu', null),
('day-special-traditional-food', 'Day Special Traditional Food', null),
('hot-drinks', 'Hot Drinks', null),
('juices', 'Juices', null),
('cold-drinks', 'Cold Drinks', null),
('beer', 'Beer', null),
('wine', 'Wine', null),
('imported-wine', 'Imported Wine', null),
('local-wine-big', 'Local Wine Big', null),
('cognac', 'Cognac', null),
('liquor', 'Liquor', null),
('premium-whisky', 'Premium Whisky', null),
('regular-whisky', 'Regular Whisky', null),
('spirits', 'Spirits', null);

INSERT INTO menu_items (id, category_id, name, description, price, image_url, rating, preparation_time, available) VALUES 
(
      'anatomy-101-slippery-nipple-x2lim', 
      'shooters', 
      'Anatomy 101 (Slippery Nipple)', 
      'Layered shot with sambuca, Irish cream, and a dash of grenadine.', 
      442, 
      'https://loremflickr.com/400/300/slippery%2Cnipple%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'culinary-arts-jell-o-shooter-1cmh9', 
      'shooters', 
      'Culinary Arts (Jell-O Shooter)', 
      'Vodka-based jell-o shooter with water and gelatin.', 
      442, 
      'https://loremflickr.com/400/300/jello%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'theology-101-flaming-jesus-iq65c', 
      'shooters', 
      'Theology 101 (Flaming Jesus)', 
      'Flaming shot with vodka, lime juice, grenadine, and 151-proof rum.', 
      442, 
      'https://loremflickr.com/400/300/flaming%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'pre-med-brain-tumor-j7tng', 
      'shooters', 
      'Pre-Med (Brain Tumor)', 
      'Coffee liqueur, vodka, Irish cream, and grenadine shooter.', 
      442, 
      'https://loremflickr.com/400/300/brain%2Ctumor%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'earth-science-mudslide-abvz1', 
      'shooters', 
      'Earth Science (Mudslide)', 
      'Vodka, Irish cream, and coffee brandy shooter.', 
      442, 
      'https://loremflickr.com/400/300/mudslide%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'drama-101-screaming-orgasm-xyx57', 
      'shooters', 
      'Drama 101 (Screaming Orgasm)', 
      'Grand Marnier, Irish cream, and coffee liqueur shooter.', 
      442, 
      'https://loremflickr.com/400/300/screaming%2Corgasm%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'forensic-medicine-red-death-rk1is', 
      'shooters', 
      'Forensic Medicine (Red Death)', 
      'Gin, cherry brandy, and dry vermouth shooter.', 
      442, 
      'https://loremflickr.com/400/300/red%2Cdeath%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      '1-shot-tequila-njg5n', 
      'shooters', 
      '1 Shot Tequila', 
      'Tequila shot with tomato juice, lemon juice, pepper, celery salt, and Tabasco.', 
      442, 
      'https://loremflickr.com/400/300/tequila%2Cshot', 
      4.5, 
      15, 
      true
    ),
(
      'civil-war-studies-alabama-slammer-6pzjk', 
      'shooters', 
      'Civil War Studies (Alabama Slammer)', 
      'Southern Comfort, Amaretto, Sloe Gin, and lemon juice shooter.', 
      442, 
      'https://loremflickr.com/400/300/alabama%2Cslammer', 
      4.5, 
      15, 
      true
    ),
(
      'civil-engineering-cement-mixer-diwcw', 
      'shooters', 
      'Civil Engineering (Cement Mixer)', 
      'Irish cream, coffee cream, and 151 rum shooter.', 
      442, 
      'https://loremflickr.com/400/300/cement%2Cmixer%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'b-52-a066h', 
      'shooters', 
      'B-52', 
      'Layered shot with Tia Maria, Baileys, Kahlua, Irish cream, and Captain Morgan.', 
      442, 
      'https://loremflickr.com/400/300/b52%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'rusty-nail-wkp24', 
      'shooters', 
      'Rusty Nail', 
      'Whisky and Drambuie served with ice.', 
      442, 
      'https://loremflickr.com/400/300/rusty%2Cnail%2Ccocktail', 
      4.5, 
      15, 
      true
    ),
(
      'psychology-vulcan-mind-probe-n908o', 
      'shooters', 
      'Psychology (Vulcan Mind Probe)', 
      'Vodka and Blue Curacao shooter.', 
      442, 
      'https://loremflickr.com/400/300/vulcan%2Cmind%2Cprobe', 
      4.5, 
      15, 
      true
    ),
(
      'human-relations-orgasm-kxdum', 
      'shooters', 
      'Human Relations (Orgasm)', 
      'Vodka, Triple Sec, lime juice, and sugar shooter.', 
      442, 
      'https://loremflickr.com/400/300/orgasm%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'hawaiian-culture-kumoniwannalaya-k9ady', 
      'shooters', 
      'Hawaiian Culture (Kumoniwannalaya)', 
      'Gin, Triple Sec, and pineapple juice shooter.', 
      442, 
      'https://loremflickr.com/400/300/hawaiian%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'first-aid-snake-bite-1fil4', 
      'shooters', 
      'First Aid (Snake Bite)', 
      'Yukon Jack and lime juice shooter.', 
      442, 
      'https://loremflickr.com/400/300/snake%2Cbite%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'oceanography-sex-on-the-beach-g8rwy', 
      'shooters', 
      'Oceanography (Sex on the Beach)', 
      'Vodka, Triple Sec, cranberry juice, and cherry brandy shooter.', 
      442, 
      'https://loremflickr.com/400/300/sex%2Con%2Cthe%2Cbeach%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'world-war-ii-studies-kamikaze-0bssc', 
      'shooters', 
      'World War II Studies (Kamikaze)', 
      'Vodka, Triple Sec, and lime juice shooter.', 
      442, 
      'https://loremflickr.com/400/300/kamikaze%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'nutrition-ear-my-cherry-oqkz5', 
      'shooters', 
      'Nutrition (Ear My Cherry)', 
      'Chambord, Irish cream, and cherry shooter.', 
      442, 
      'https://loremflickr.com/400/300/cherry%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'aeronautics-b-52-0vaoo', 
      'shooters', 
      'Aeronautics (B-52)', 
      'Kahlua, Black Label, Tia Maria, and Baileys layered shot.', 
      442, 
      'https://loremflickr.com/400/300/b52%2Clayered%2Cshot', 
      4.5, 
      15, 
      true
    ),
(
      'study-hall-mind-eraser-6gqe3', 
      'shooters', 
      'Study Hall (Mind Eraser)', 
      'Vodka, 151 rum, Midori, and lime juice shooter.', 
      442, 
      'https://loremflickr.com/400/300/mind%2Ceraser%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'co-ed-gym-hop-skip-go-naked-thywi', 
      'shooters', 
      'Co-Ed Gym (Hop Skip & Go Naked)', 
      'Light rum, vodka, apricot brandy, grenadine, and lime juice shooter.', 
      442, 
      'https://loremflickr.com/400/300/hop%2Cskip%2Cgo%2Cnaked', 
      4.5, 
      15, 
      true
    ),
(
      'after-five-zejm1', 
      'shooters', 
      'After Five', 
      'Peppermint schnapps, Irish cream, and Kahlua shooter.', 
      442, 
      'https://loremflickr.com/400/300/after%2Cfive%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'hot-shot-6cupx', 
      'shooters', 
      'Hot Shot', 
      'Peppermint schnapps and vodka shooter.', 
      442, 
      'https://loremflickr.com/400/300/hot%2Cshot', 
      4.5, 
      15, 
      true
    ),
(
      'home-coming-dn0ph', 
      'shooters', 
      'Home Coming', 
      'Irish cream and Amaretto shooter.', 
      442, 
      'https://loremflickr.com/400/300/home%2Ccoming%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'mudslide-dskho', 
      'shooters', 
      'Mudslide', 
      'Irish cream, Kahlua, and vodka shooter.', 
      442, 
      'https://loremflickr.com/400/300/mudslide', 
      4.5, 
      15, 
      true
    ),
(
      'alabama-slammer-h3a6h', 
      'shooters', 
      'Alabama Slammer', 
      'Orange juice, Southern Comfort, Amaretto, and Sloe Gin shooter.', 
      442, 
      'https://loremflickr.com/400/300/alabama%2Cslammer', 
      4.5, 
      15, 
      true
    ),
(
      'lobe-job-vk3ov', 
      'shooters', 
      'Lobe Job', 
      'Irish cream and vodka shooter.', 
      442, 
      'https://loremflickr.com/400/300/lobe%2Cjob%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'sex-on-the-beach-flr34', 
      'shooters', 
      'Sex on the Beach', 
      'Peach schnapps, vodka, Triple Sec, and pineapple juice shooter.', 
      442, 
      'https://loremflickr.com/400/300/sex%2Con%2Cthe%2Cbeach', 
      4.5, 
      15, 
      true
    ),
(
      'bubble-gum-rvrfv', 
      'shooters', 
      'Bubble Gum', 
      'Peach schnapps, orange juice, banana liquor, and vodka shooter.', 
      442, 
      'https://loremflickr.com/400/300/bubble%2Cgum%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'cerebral-hummorange-hfhj6', 
      'shooters', 
      'Cerebral Hummorange', 
      'Irish cream, peach schnapps, and Kahlua shooter.', 
      442, 
      'https://loremflickr.com/400/300/cerebral%2Chummorange', 
      4.5, 
      15, 
      true
    ),
(
      'indian-summer-qo407', 
      'shooters', 
      'Indian Summer', 
      'Kahlua, vodka, and pineapple juice shooter.', 
      442, 
      'https://loremflickr.com/400/300/indian%2Csummer%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'after-eight-b4pjm', 
      'shooters', 
      'After Eight', 
      'Irish cream, Kahlua, and white creme de menthe shooter.', 
      442, 
      'https://loremflickr.com/400/300/after%2Ceight%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'midnight-sun-h21nh', 
      'shooters', 
      'Midnight Sun', 
      'Grenadine and vodka shooter.', 
      442, 
      'https://loremflickr.com/400/300/midnight%2Csun%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'killer-cool-aid-a0ev4', 
      'shooters', 
      'Killer Cool Aid', 
      'Amaretto, peach schnapps, vodka, and cranberry juice shooter.', 
      442, 
      'https://loremflickr.com/400/300/killer%2Ccool%2Caid', 
      4.5, 
      15, 
      true
    ),
(
      'mocha-mint-18c92', 
      'shooters', 
      'Mocha Mint', 
      'White creme de cacao, white creme de menthe, and Kahlua shooter.', 
      442, 
      'https://loremflickr.com/400/300/mocha%2Cmint%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'panther-wau2a', 
      'shooters', 
      'Panther', 
      'Peppermint schnapps and tequila shooter.', 
      442, 
      'https://loremflickr.com/400/300/panther%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'anti-freeze-hewsw', 
      'shooters', 
      'Anti Freeze', 
      'Vodka and green creme de menthe shooter.', 
      442, 
      'https://loremflickr.com/400/300/anti%2Cfreeze%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'deep-throat-n4i0c', 
      'shooters', 
      'Deep Throat', 
      'Vodka and Kahlua shooter.', 
      442, 
      'https://loremflickr.com/400/300/deep%2Cthroat%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'buffalo-sweat-qvow6', 
      'shooters', 
      'Buffalo Sweat', 
      'Tabasco sauce and bourbon shooter.', 
      442, 
      'https://loremflickr.com/400/300/buffalo%2Csweat%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'nutty-irishman-1q1ui', 
      'shooters', 
      'Nutty Irishman', 
      'Frangelico and Irish cream shooter.', 
      442, 
      'https://loremflickr.com/400/300/nutty%2Cirishman', 
      4.5, 
      15, 
      true
    ),
(
      'chocolate-covered-cherry-qgnhb', 
      'shooters', 
      'Chocolate Covered Cherry', 
      'White creme de cacao, Amaretto, and Kahlua shooter.', 
      442, 
      'https://loremflickr.com/400/300/chocolate%2Ccovered%2Ccherry', 
      4.5, 
      15, 
      true
    ),
(
      '57-chevy-qx9jt', 
      'shooters', 
      '57 Chevy', 
      'Vodka and white creme de cacao shooter.', 
      442, 
      'https://loremflickr.com/400/300/57%2Cchevy%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'pink-lemonade-gmr7w', 
      'shooters', 
      'Pink Lemonade', 
      'Sour mix, cranberry juice, and vodka shooter.', 
      442, 
      'https://loremflickr.com/400/300/pink%2Clemonade%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'snow-cap-0gr38', 
      'shooters', 
      'Snow Cap', 
      'Tequila and Irish cream shooter.', 
      442, 
      'https://loremflickr.com/400/300/snow%2Ccap%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'ground-zero-lms15', 
      'shooters', 
      'Ground Zero', 
      'Kahlua, vodka, peppermint schnapps, and bourbon shooter.', 
      442, 
      'https://loremflickr.com/400/300/ground%2Czero%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'prairie-five-2w6nl', 
      'shooters', 
      'Prairie Five', 
      'Tabasco sauce and tequila shooter.', 
      442, 
      'https://loremflickr.com/400/300/prairie%2Cfive%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'woo-woo-4rymp', 
      'shooters', 
      'Woo Woo', 
      'Peach schnapps and cranberry juice shooter.', 
      442, 
      'https://loremflickr.com/400/300/woo%2Cwoo%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'iguana-9ryjr', 
      'shooters', 
      'Iguana', 
      'Kahlua, vodka, tequila, and sour mix shooter.', 
      442, 
      'https://loremflickr.com/400/300/iguana%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'brain-eraser-x0fdg', 
      'shooters', 
      'Brain Eraser', 
      'Amaretto, Kahlua, club soda, and vodka shooter.', 
      442, 
      'https://loremflickr.com/400/300/brain%2Ceraser', 
      4.5, 
      15, 
      true
    );

INSERT INTO menu_items (id, category_id, name, description, price, image_url, rating, preparation_time, available) VALUES 
(
      'russian-quaalude-hbvji', 
      'shooters', 
      'Russian Quaalude', 
      'Vodka, Irish cream, and grenadine shooter.', 
      442, 
      'https://loremflickr.com/400/300/russian%2Cquaalude', 
      4.5, 
      15, 
      true
    ),
(
      'hot-pants-1jzl5', 
      'shooters', 
      'Hot Pants', 
      'Grapefruit juice, peppermint schnapps, and Kahlua shooter.', 
      442, 
      'https://loremflickr.com/400/300/hot%2Cpants%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'sea-breeze-8n386', 
      'shooters', 
      'Sea Breeze', 
      'Vodka, cranberry juice, and grapefruit juice shooter.', 
      442, 
      'https://loremflickr.com/400/300/sea%2Cbreeze', 
      4.5, 
      15, 
      true
    ),
(
      'candy-bar-ew7s2', 
      'shooters', 
      'Candy Bar', 
      'Frangelico and vodka shooter.', 
      442, 
      'https://loremflickr.com/400/300/candy%2Cbar%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'cement-mixer-5hvrx', 
      'shooters', 
      'Cement Mixer', 
      'Lime juice and Irish cream shooter.', 
      442, 
      'https://loremflickr.com/400/300/cement%2Cmixer', 
      4.5, 
      15, 
      true
    ),
(
      'lion-tamer-aqgop', 
      'shooters', 
      'Lion Tamer', 
      'Lime juice and Southern Comfort shooter.', 
      442, 
      'https://loremflickr.com/400/300/lion%2Ctamer%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'banana-boat-c42uo', 
      'shooters', 
      'Banana Boat', 
      'Lime juice, banana liquor, and tequila shooter.', 
      442, 
      'https://loremflickr.com/400/300/banana%2Cboat%2Cshooter', 
      4.5, 
      15, 
      true
    ),
(
      'kamikaze-e80k4', 
      'long-cocktails', 
      'Kamikaze', 
      'Vodka, Bacardi, gin, tequila, Cointreau, lemon juice, and Triple Sec.', 
      442, 
      'https://loremflickr.com/400/300/kamikaze%2Ccocktail', 
      4.5, 
      15, 
      true
    ),
(
      'long-island-kv9zw', 
      'long-cocktails', 
      'Long Island', 
      'Vodka, gin, light rum, sour mix, and Coca-Cola shaken with ice.', 
      442, 
      'https://loremflickr.com/400/300/long%2Cisland%2Ciced%2Ctea', 
      4.5, 
      15, 
      true
    ),
(
      'margarita-ywspa', 
      'long-cocktails', 
      'Margarita', 
      'Tequila, Cointreau, lemon juice with salt on the rim.', 
      442, 
      'https://loremflickr.com/400/300/margarita', 
      4.5, 
      15, 
      true
    ),
(
      'between-the-sheets-weodv', 
      'long-cocktails', 
      'Between the Sheets', 
      'Cointreau, cognac, Bacardi rum, and lemon juice shaken with ice.', 
      442, 
      'https://loremflickr.com/400/300/between%2Cthe%2Csheets%2Ccocktail', 
      4.5, 
      15, 
      true
    ),
(
      'kiss-me-quick-rlmcr', 
      'long-cocktails', 
      'Kiss Me Quick', 
      'Pernod, Cointreau, Angostura bitters with ice and Ambo water.', 
      442, 
      'https://loremflickr.com/400/300/kiss%2Cme%2Cquick%2Ccocktail', 
      4.5, 
      15, 
      true
    ),
(
      'tequila-sunrise-4h3mc', 
      'long-cocktails', 
      'Tequila Sunrise', 
      'Tequila White, orange juice, and grenadine vermouth.', 
      442, 
      'https://loremflickr.com/400/300/tequila%2Csunrise', 
      4.5, 
      15, 
      true
    ),
(
      'apple-martini-sxuyc', 
      'long-cocktails', 
      'Apple Martini', 
      'Triple Sec, vodka, apple juice, cherry brandy, and apple flavor vodka with ice.', 
      442, 
      'https://loremflickr.com/400/300/apple%2Cmartini', 
      4.5, 
      15, 
      true
    ),
(
      'black-russian-ccsl2', 
      'long-cocktails', 
      'Black Russian', 
      'Kahlua and vodka served with ice.', 
      442, 
      'https://loremflickr.com/400/300/black%2Crussian', 
      4.5, 
      15, 
      true
    ),
(
      'frozen-daiquiri-zhzkm', 
      'long-cocktails', 
      'Frozen Daiquiri', 
      'Bacardi rum and sweet juice served with ice.', 
      442, 
      'https://loremflickr.com/400/300/frozen%2Cdaiquiri', 
      4.5, 
      15, 
      true
    ),
(
      'pick-me-up-g2y9u', 
      'long-cocktails', 
      'Pick Me Up', 
      'Cognac, milk, sugar, and Angostura bitters shaken with ice, topped with Ambo.', 
      442, 
      'https://loremflickr.com/400/300/pick%2Cme%2Cup%2Ccocktail', 
      4.5, 
      15, 
      true
    ),
(
      'irish-coffee-hgotr', 
      'long-cocktails', 
      'Irish Coffee', 
      'Irish whisky, sugar, strong coffee topped with whipped cream.', 
      442, 
      'https://loremflickr.com/400/300/irish%2Ccoffee', 
      4.5, 
      15, 
      true
    ),
(
      'screwdriver-cd1ot', 
      'long-cocktails', 
      'Screwdriver', 
      'Vodka, fresh orange juice, and sugar shaken with ice, decorated with orange slice.', 
      442, 
      'https://loremflickr.com/400/300/screwdriver%2Ccocktail', 
      4.5, 
      15, 
      true
    ),
(
      'golf-tlq2s', 
      'long-cocktails', 
      'Golf', 
      'Gin, dry vermouth, and Angostura bitters with ice.', 
      442, 
      'https://loremflickr.com/400/300/golf%2Ccocktail', 
      4.5, 
      15, 
      true
    ),
(
      'pina-colada-77whu', 
      'long-cocktails', 
      'Pina Colada', 
      'Malibu, powdered milk, pineapple juice with crushed ice.', 
      442, 
      'https://loremflickr.com/400/300/pina%2Ccolada', 
      4.5, 
      15, 
      true
    ),
(
      'caribbean-drink-jms8t', 
      'long-cocktails', 
      'Caribbean Drink', 
      'Malibu, Cointreau, Bacardi White, red martini, orange, sugar with crushed ice.', 
      442, 
      'https://loremflickr.com/400/300/caribbean%2Cdrink', 
      4.5, 
      15, 
      true
    ),
(
      'gin-fizz-f7dww', 
      'long-cocktails', 
      'Gin Fizz', 
      'Gin, lemon juice, sugar served with ice and topped with Ambo.', 
      442, 
      'https://loremflickr.com/400/300/gin%2Cfizz', 
      4.5, 
      15, 
      true
    ),
(
      'gin-swizzle-83uhz', 
      'long-cocktails', 
      'Gin Swizzle', 
      'Gin, lemon juice, sugar syrup, and Angostura bitters with ice.', 
      442, 
      'https://loremflickr.com/400/300/gin%2Cswizzle', 
      4.5, 
      15, 
      true
    ),
(
      'red-lion-3vzqo', 
      'long-cocktails', 
      'Red Lion', 
      'Gin, Grand Marnier, lemon juice with ice, glass decorated with sugar powder.', 
      442, 
      'https://loremflickr.com/400/300/red%2Clion%2Ccocktail', 
      4.5, 
      15, 
      true
    ),
(
      'churchill-3m019', 
      'long-cocktails', 
      'Churchill', 
      'Whisky, lemon juice, red vermouth, and Cointreau with ice.', 
      442, 
      'https://loremflickr.com/400/300/churchill%2Ccocktail', 
      4.5, 
      15, 
      true
    ),
(
      'rob-roy-z5bfy', 
      'long-cocktails', 
      'Rob Roy', 
      'Whisky and red vermouth with ice if desired.', 
      442, 
      'https://loremflickr.com/400/300/rob%2Croy%2Ccocktail', 
      4.5, 
      15, 
      true
    ),
(
      'bloody-mary-gbikp', 
      'long-cocktails', 
      'Bloody Mary', 
      'Vodka, tomato juice, black pepper with ice.', 
      442, 
      'https://loremflickr.com/400/300/bloody%2Cmary', 
      4.5, 
      15, 
      true
    ),
(
      'alexander-f99fg', 
      'long-cocktails', 
      'Alexander', 
      'Cognac, creme de Kahlua, and Irish cream with ice.', 
      442, 
      'https://loremflickr.com/400/300/alexander%2Ccocktail', 
      4.5, 
      15, 
      true
    ),
(
      'americano-pahr8', 
      'long-cocktails', 
      'Americano', 
      'Red vermouth, Campari bitters, lemon juice with ice.', 
      442, 
      'https://loremflickr.com/400/300/americano%2Ccocktail', 
      4.5, 
      15, 
      true
    ),
(
      'negroni-l3zdj', 
      'long-cocktails', 
      'Negroni', 
      'Gin, Campari bitters, red vermouth, lemon juice with ice.', 
      442, 
      'https://loremflickr.com/400/300/negroni', 
      4.5, 
      15, 
      true
    ),
(
      'pink-lady-hfozs', 
      'long-cocktails', 
      'Pink Lady', 
      'Gin, egg white, sugar syrup, and vimto or grenadine shaken with ice.', 
      442, 
      'https://loremflickr.com/400/300/pink%2Clady%2Ccocktail', 
      4.5, 
      15, 
      true
    ),
(
      'orange-blossom-9k9sy', 
      'long-cocktails', 
      'Orange Blossom', 
      'Gin and fresh orange juice shaken with ice.', 
      442, 
      'https://loremflickr.com/400/300/orange%2Cblossom%2Ccocktail', 
      4.5, 
      15, 
      true
    ),
(
      'manhattan-63n9a', 
      'long-cocktails', 
      'Manhattan', 
      'Whisky and martini (dry or rosso) served with ice.', 
      442, 
      'https://loremflickr.com/400/300/manhattan%2Ccocktail', 
      4.5, 
      15, 
      true
    ),
(
      'cuba-libre-c2rhj', 
      'long-cocktails', 
      'Cuba Libre', 
      'Bacardi White rum, lemon juice, Coca-Cola with ice.', 
      442, 
      'https://loremflickr.com/400/300/cuba%2Clibre', 
      4.5, 
      15, 
      true
    ),
(
      'white-russian-z1j0b', 
      'long-cocktails', 
      'White Russian', 
      'Vodka, Kahlua, and pure cream served with ice.', 
      442, 
      'https://loremflickr.com/400/300/white%2Crussian', 
      4.5, 
      15, 
      true
    ),
(
      'chicken-fried-steak-t4x5i', 
      'special-menu', 
      'Chicken Fried Steak', 
      'Cubed chicken, flour, black pepper, egg, and bread crumbs.', 
      1800, 
      'https://loremflickr.com/400/300/chicken%2Cfried%2Csteak', 
      4.5, 
      15, 
      true
    ),
(
      'fried-nile-perch-with-cheese-f4do0', 
      'special-menu', 
      'Fried Nile Perch with Cheese', 
      'Flour, cheese, and oil fried Nile perch.', 
      1800, 
      'https://loremflickr.com/400/300/fried%2Cnile%2Cperch%2Ccheese', 
      4.5, 
      15, 
      true
    ),
(
      'classic-beef-43p9u', 
      'special-menu', 
      'Classic Beef', 
      'Cream, spaghetti, green pepper, and mushroom.', 
      1800, 
      'https://loremflickr.com/400/300/classic%2Cbeef%2Cpasta', 
      4.5, 
      15, 
      true
    ),
(
      'combo-special-o6411', 
      'special-menu', 
      'Combo Special', 
      'Grilled BBQ chicken with spaghetti meat sauce.', 
      1800, 
      'https://loremflickr.com/400/300/combo%2Cspecial%2Cgrilled%2Cchicken', 
      4.5, 
      15, 
      true
    ),
(
      'mixed-salad-madrid-style-n1e4k', 
      'salads', 
      'Mixed Salad Madrid Style', 
      'Lettuce, tuna, ring onion, boiled eggs, black olives, tomatoes, and olive oil.', 
      619, 
      'https://loremflickr.com/400/300/mixed%2Csalad%2Cmadrid%2Cstyle', 
      4.5, 
      15, 
      true
    ),
(
      'valencian-salad-123p3', 
      'salads', 
      'Valencian Salad', 
      'Orange, tomato, cheese, avocado, and black olives.', 
      719, 
      'https://loremflickr.com/400/300/valencian%2Csalad', 
      4.5, 
      15, 
      true
    ),
(
      'italian-salad-gtocw', 
      'salads', 
      'Italian Salad', 
      'Lettuce, tomato, cheeses, mortadella, and boiled beef.', 
      719, 
      'https://loremflickr.com/400/300/italian%2Csalad', 
      4.5, 
      15, 
      true
    ),
(
      'chicken-salad-x9rl4', 
      'salads', 
      'Chicken Salad', 
      'Julienne of boiled chicken, onion, green pepper, lettuce, and mayonnaise.', 
      719, 
      'https://loremflickr.com/400/300/chicken%2Csalad', 
      4.5, 
      15, 
      true
    ),
(
      'tuna-salad-wsdua', 
      'salads', 
      'Tuna Salad', 
      'Flaked tuna, green pepper, white onion, tomato, and vinaigrette dressing.', 
      819, 
      'https://loremflickr.com/400/300/tuna%2Csalad', 
      4.5, 
      15, 
      true
    ),
(
      'rodeo-special-salad-t20dc', 
      'salads', 
      'Rodeo Special Salad', 
      'Potato, carrot, boiled meat, french beans, sausages, green pepper, cheese, and mayonnaise.', 
      819, 
      'https://loremflickr.com/400/300/rodeo%2Cspecial%2Csalad', 
      4.5, 
      15, 
      true
    ),
(
      'mixed-salad-4t0ui', 
      'salads', 
      'Mixed Salad', 
      'Lettuce, tomato, green pepper, onion, and vinaigrette dressing.', 
      719, 
      'https://loremflickr.com/400/300/mixed%2Csalad', 
      4.5, 
      15, 
      true
    ),
(
      'thick-cream-soup-klvsb', 
      'soups', 
      'Thick Cream Soup', 
      'Choice of chicken cream, mushroom cream, onion cream, or asparagus cream.', 
      619, 
      'https://loremflickr.com/400/300/cream%2Csoup', 
      4.5, 
      15, 
      true
    ),
(
      'thin-soup-c64ie', 
      'soups', 
      'Thin Soup', 
      'Consomme (chicken or beef), french onion, or vegetable soup.', 
      319, 
      'https://loremflickr.com/400/300/consomme%2Csoup', 
      4.5, 
      15, 
      true
    ),
(
      'pasta-primavera-w81nw', 
      'pasta', 
      'Pasta Primavera', 
      'Spaghetti, tagliatelle, or penne with vegetables and pea.', 
      740, 
      'https://loremflickr.com/400/300/pasta%2Cprimavera', 
      4.5, 
      15, 
      true
    );

INSERT INTO menu_items (id, category_id, name, description, price, image_url, rating, preparation_time, available) VALUES 
(
      'pasta-special-sauce-8gf6w', 
      'pasta', 
      'Pasta Special Sauce', 
      'Spaghetti, tagliatelle, or penne with special sauce.', 
      919, 
      'https://loremflickr.com/400/300/pasta%2Cspecial%2Csauce', 
      4.5, 
      15, 
      true
    ),
(
      'pasta-napolitane-k82bi', 
      'pasta', 
      'Pasta Napolitane', 
      'Spaghetti, tagliatelle, or penne with napolitane sauce.', 
      740, 
      'https://loremflickr.com/400/300/pasta%2Cnapolitane', 
      4.5, 
      15, 
      true
    ),
(
      'pasta-carbonara-pkvd9', 
      'pasta', 
      'Pasta Carbonara', 
      'Spaghetti, tagliatelle, or penne with carbonara sauce.', 
      740, 
      'https://loremflickr.com/400/300/pasta%2Ccarbonara', 
      4.5, 
      15, 
      true
    ),
(
      'pasta-tomato-sauce-03fhn', 
      'pasta', 
      'Pasta Tomato Sauce', 
      'Spaghetti, tagliatelle, or penne with tomato sauce.', 
      620, 
      'https://loremflickr.com/400/300/pasta%2Ctomato%2Csauce', 
      4.5, 
      15, 
      true
    ),
(
      'pasta-meat-sauce-w1oof', 
      'pasta', 
      'Pasta Meat Sauce', 
      'Spaghetti, tagliatelle, or penne with meat sauce.', 
      740, 
      'https://loremflickr.com/400/300/pasta%2Cmeat%2Csauce', 
      4.5, 
      15, 
      true
    ),
(
      'pasta-tuna-fish-sauce-7rfqt', 
      'pasta', 
      'Pasta Tuna Fish Sauce', 
      'Spaghetti, tagliatelle, or penne with tuna fish sauce.', 
      919, 
      'https://loremflickr.com/400/300/pasta%2Ctuna%2Csauce', 
      4.5, 
      15, 
      true
    ),
(
      'pasta-arabiata-rp49x', 
      'pasta', 
      'Pasta Arabiata', 
      'Spaghetti, tagliatelle, or penne with arrabbiata sauce.', 
      640, 
      'https://loremflickr.com/400/300/pasta%2Carrabbiata', 
      4.5, 
      15, 
      true
    ),
(
      'home-made-fresh-lasagna-7opuf', 
      'pasta', 
      'Home-made Fresh Lasagna', 
      'Fresh homemade lasagna.', 
      1200, 
      'https://loremflickr.com/400/300/fresh%2Clasagna', 
      4.5, 
      15, 
      true
    ),
(
      'rice-with-vegetables-c315m', 
      'rice-dishes', 
      'Rice with Vegetables', 
      'Rice served with mixed vegetables.', 
      699, 
      'https://loremflickr.com/400/300/rice%2Cvegetables', 
      4.5, 
      15, 
      true
    ),
(
      'assorted-rice-with-vegetables-egg-52qly', 
      'rice-dishes', 
      'Assorted Rice with Vegetables & Egg', 
      'Assorted rice with vegetables and egg.', 
      719, 
      'https://loremflickr.com/400/300/assorted%2Crice%2Cvegetables%2Cegg', 
      4.5, 
      15, 
      true
    ),
(
      'rice-with-egg-9mmxq', 
      'rice-dishes', 
      'Rice with Egg', 
      'Rice served with egg.', 
      519, 
      'https://loremflickr.com/400/300/rice%2Cegg', 
      4.5, 
      15, 
      true
    ),
(
      'rice-with-beef-meat-mt7rq', 
      'rice-dishes', 
      'Rice with Beef Meat', 
      'Rice served with beef meat.', 
      719, 
      'https://loremflickr.com/400/300/rice%2Cbeef', 
      4.5, 
      15, 
      true
    ),
(
      'rice-a-la-greek-3t84s', 
      'rice-dishes', 
      'Rice a la Greek', 
      'Rice, beef, mortadella, cheese, and mushroom.', 
      919, 
      'https://loremflickr.com/400/300/greek%2Crice', 
      4.5, 
      15, 
      true
    ),
(
      'spanish-rice-mipv9', 
      'rice-dishes', 
      'Spanish Rice', 
      'Boiled rice, sausage, mushroom, green pepper, and spinach.', 
      919, 
      'https://loremflickr.com/400/300/spanish%2Crice', 
      4.5, 
      15, 
      true
    ),
(
      'rice-with-chicken-vrydt', 
      'rice-dishes', 
      'Rice with Chicken', 
      'Rice served with chicken.', 
      819, 
      'https://loremflickr.com/400/300/rice%2Cchicken', 
      4.5, 
      15, 
      true
    ),
(
      'rice-with-fish-56kaz', 
      'rice-dishes', 
      'Rice with Fish', 
      'Rice served with fish.', 
      819, 
      'https://loremflickr.com/400/300/rice%2Cfish', 
      4.5, 
      15, 
      true
    ),
(
      'rice-spinach-yoz7i', 
      'rice-dishes', 
      'Rice Spinach', 
      'Rice served with spinach.', 
      719, 
      'https://loremflickr.com/400/300/rice%2Cspinach', 
      4.5, 
      15, 
      true
    ),
(
      'rice-mushroom-zgbm2', 
      'rice-dishes', 
      'Rice Mushroom', 
      'Rice served with mushroom.', 
      719, 
      'https://loremflickr.com/400/300/rice%2Cmushroom', 
      4.5, 
      15, 
      true
    ),
(
      'rice-with-tuna-fmrww', 
      'rice-dishes', 
      'Rice with Tuna', 
      'Rice served with tuna.', 
      919, 
      'https://loremflickr.com/400/300/rice%2Ctuna', 
      4.5, 
      15, 
      true
    ),
(
      'rice-with-brown-sauce-6n6ek', 
      'rice-dishes', 
      'Rice with Brown Sauce', 
      'Rice served with brown sauce.', 
      619, 
      'https://loremflickr.com/400/300/rice%2Cbrown%2Csauce', 
      4.5, 
      15, 
      true
    ),
(
      'beef-fillet-slices-with-oyster-sauce-mzwsy', 
      'beef-dishes', 
      'Beef Fillet Slices with Oyster Sauce', 
      'Slices of filet beef with oyster sauce.', 
      1110, 
      'https://loremflickr.com/400/300/beef%2Cfillet%2Coyster%2Csauce', 
      4.5, 
      15, 
      true
    ),
(
      'beef-stroganoff-u7sd4', 
      'beef-dishes', 
      'Beef Stroganoff', 
      'Julienne of beef fillet with cream.', 
      1110, 
      'https://loremflickr.com/400/300/beef%2Cstroganoff', 
      4.5, 
      15, 
      true
    ),
(
      'cordon-bleu-b7ryu', 
      'beef-dishes', 
      'Cordon Bleu', 
      'Tender veal meat, slices of ham and cheese with recommended sauce.', 
      1110, 
      'https://loremflickr.com/400/300/cordon%2Cbleu', 
      4.5, 
      15, 
      true
    ),
(
      'pepper-steak-pk06t', 
      'beef-dishes', 
      'Pepper Steak', 
      'Steak with pepper sauce.', 
      1110, 
      'https://loremflickr.com/400/300/pepper%2Csteak', 
      4.5, 
      15, 
      true
    ),
(
      'steak-rodeo-r3ylm', 
      'beef-dishes', 
      'Steak Rodeo', 
      'Special Rodeo style steak.', 
      1110, 
      'https://loremflickr.com/400/300/steak%2Crodeo', 
      4.5, 
      15, 
      true
    ),
(
      'chateaubriand-steak-sc0hj', 
      'beef-dishes', 
      'Chateaubriand Steak', 
      'Well marinated beef fillet with demi-glace based sauce.', 
      1110, 
      'https://loremflickr.com/400/300/chateaubriand%2Csteak', 
      4.5, 
      15, 
      true
    ),
(
      'flambe-coffee-beef-steak-h5ge8', 
      'beef-dishes', 
      'Flambe Coffee Beef Steak', 
      'Dusted with coffee powder and ignited on fire for unique flavor.', 
      1110, 
      'https://loremflickr.com/400/300/flambe%2Ccoffee%2Csteak', 
      4.5, 
      15, 
      true
    ),
(
      'fillet-steak-with-red-wine-sauce-w1dak', 
      'beef-dishes', 
      'Fillet Steak with Red Wine Sauce', 
      'Beef fillet with red wine sauce.', 
      1110, 
      'https://loremflickr.com/400/300/fillet%2Csteak%2Cred%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'chilli-beef-fillet-with-assorted-rice-x27x4', 
      'beef-dishes', 
      'Chilli Beef Fillet with Assorted Rice', 
      'Slices of beef fillet with chilli sauce, a little bit hot.', 
      1110, 
      'https://loremflickr.com/400/300/chilli%2Cbeef%2Cfillet', 
      4.5, 
      15, 
      true
    ),
(
      'fillet-steak-with-beurre-maitre-d-hotel-s7w36', 
      'beef-dishes', 
      'Fillet Steak with Beurre Maitre d''Hotel', 
      'Well marinated beef fillet topped with hard butter sauce.', 
      1110, 
      'https://loremflickr.com/400/300/fillet%2Csteak%2Cbeurre', 
      4.5, 
      15, 
      true
    ),
(
      'sliced-simmered-beef-steak-with-vegetables-slopa', 
      'beef-dishes', 
      'Sliced Simmered Beef Steak with Vegetables', 
      'Sliced simmered beef steak with vegetables.', 
      1110, 
      'https://loremflickr.com/400/300/simmered%2Cbeef%2Csteak%2Cvegetables', 
      4.5, 
      15, 
      true
    ),
(
      'tournedos-with-mushroom-sauce-mzqzo', 
      'beef-dishes', 
      'Tournedos with Mushroom Sauce', 
      'Very juicy beef fillet steak coated with tasty mushroom sauce.', 
      1110, 
      'https://loremflickr.com/400/300/tournedos%2Cmushroom%2Csauce', 
      4.5, 
      15, 
      true
    ),
(
      'roast-chicken-2nwuo', 
      'chicken-dishes', 
      'Roast Chicken', 
      'Fresh well marinated oven roasted chicken served with roast gravy and sweet chilli sauce.', 
      1080, 
      'https://loremflickr.com/400/300/roast%2Cchicken', 
      4.5, 
      15, 
      true
    ),
(
      'stir-fried-chicken-chinese-style-43viv', 
      'chicken-dishes', 
      'Stir Fried Chicken Chinese Style', 
      'Julienne of chicken meat and vegetables, flavored with soy sauce.', 
      1080, 
      'https://loremflickr.com/400/300/stir%2Cfried%2Cchicken%2Cchinese', 
      4.5, 
      15, 
      true
    ),
(
      'chicken-saute-chasseur-5tqxt', 
      'chicken-dishes', 
      'Chicken Saute Chasseur', 
      'Cuts of chicken with chasseur sauce.', 
      1080, 
      'https://loremflickr.com/400/300/chicken%2Cchasseur', 
      4.5, 
      15, 
      true
    ),
(
      'chicken-saute-with-mushroom-9ve0k', 
      'chicken-dishes', 
      'Chicken Saute with Mushroom', 
      'Cuts of chicken pieces with mushroom sauce.', 
      1080, 
      'https://loremflickr.com/400/300/chicken%2Cmushroom', 
      4.5, 
      15, 
      true
    ),
(
      'lemon-garlic-filled-chicken-breast-hljh2', 
      'chicken-dishes', 
      'Lemon & Garlic Filled Chicken Breast', 
      'Flat chicken breasts filled with lemon and garlic butter spread.', 
      1080, 
      'https://loremflickr.com/400/300/lemon%2Cgarlic%2Cchicken%2Cbreast', 
      4.5, 
      15, 
      true
    ),
(
      'grilled-chicken-breast-with-mustard-sauce-2tiem', 
      'chicken-dishes', 
      'Grilled Chicken Breast with Mustard Sauce', 
      'Grilled chicken breast with mustard sauce.', 
      1080, 
      'https://loremflickr.com/400/300/grilled%2Cchicken%2Cmustard', 
      4.5, 
      15, 
      true
    ),
(
      'chicken-cacciatore-046ne', 
      'chicken-dishes', 
      'Chicken Cacciatore', 
      'Cuts of chicken pieces and gravy sauce.', 
      1110, 
      'https://loremflickr.com/400/300/chicken%2Ccacciatore', 
      4.5, 
      15, 
      true
    ),
(
      'curried-chicken-with-rice-e8i78', 
      'chicken-dishes', 
      'Curried Chicken with Rice', 
      'Indian dish with diced fried chicken meat with curry sauce.', 
      1110, 
      'https://loremflickr.com/400/300/curried%2Cchicken%2Crice', 
      4.5, 
      15, 
      true
    ),
(
      'half-grilled-chicken-with-mushroom-cream-sauce-j5fsy', 
      'chicken-dishes', 
      'Half Grilled Chicken with Mushroom Cream Sauce', 
      'Marinated breast and leg of chicken grilled with mushroom cream sauce.', 
      1110, 
      'https://loremflickr.com/400/300/grilled%2Cchicken%2Cmushroom%2Ccream', 
      4.5, 
      15, 
      true
    ),
(
      'chicken-cutlets-with-garlic-herbed-butter-sauce-ehu9w', 
      'chicken-dishes', 
      'Chicken Cutlets with Garlic Herbed Butter Sauce', 
      'Chicken cutlets with garlic herbed butter sauce.', 
      1110, 
      'https://loremflickr.com/400/300/chicken%2Ccutlets%2Cgarlic%2Cbutter', 
      4.5, 
      15, 
      true
    ),
(
      'brochette-of-chicken-ipjn8', 
      'chicken-dishes', 
      'Brochette of Chicken', 
      'Marinated cubes of chicken meat, onion, pepper skewed, grilled and served on top of rice.', 
      1110, 
      'https://loremflickr.com/400/300/chicken%2Cbrochette', 
      4.5, 
      15, 
      true
    ),
(
      'olive-citrus-lamb-roast-f93jj', 
      'lamb-dishes', 
      'Olive Citrus Lamb Roast', 
      'Slice of roast lamb, roast gravy sauce with black olive and citrus flavor.', 
      1110, 
      'https://loremflickr.com/400/300/olive%2Ccitrus%2Clamb%2Croast', 
      4.5, 
      15, 
      true
    ),
(
      'austrian-style-lamb-roast-vegetables-urqxo', 
      'lamb-dishes', 
      'Austrian Style Lamb Roast & Vegetables', 
      'Spanish style roast lamb served with vegetables.', 
      1110, 
      'https://loremflickr.com/400/300/austrian%2Clamb%2Croast', 
      4.5, 
      15, 
      true
    ),
(
      'ethiopian-style-roast-lamb-0ua2l', 
      'lamb-dishes', 
      'Ethiopian Style Roast Lamb', 
      'Marinated with hot spices and well flavored sauce, a little bit hot.', 
      1110, 
      'https://loremflickr.com/400/300/ethiopian%2Clamb%2Croast', 
      4.5, 
      15, 
      true
    ),
(
      'stir-fried-lamb-yisg1', 
      'lamb-dishes', 
      'Stir Fried Lamb', 
      'Julienne of lamb meat and vegetables flavored with soy sauce.', 
      1110, 
      'https://loremflickr.com/400/300/stir%2Cfried%2Clamb', 
      4.5, 
      15, 
      true
    ),
(
      'brochette-of-lamb-nkc43', 
      'lamb-dishes', 
      'Brochette of Lamb', 
      'Cubes of marinated lamb meat, onion and pepper skewed, grilled and served on top of rice.', 
      1110, 
      'https://loremflickr.com/400/300/lamb%2Cbrochette', 
      4.5, 
      15, 
      true
    ),
(
      'grilled-nile-perch-with-recommended-sauce-15ge2', 
      'fish-dishes', 
      'Grilled Nile Perch with Recommended Sauce', 
      'Grilled Nile perch with recommended sauce.', 
      1400, 
      'https://loremflickr.com/400/300/grilled%2Cnile%2Cperch', 
      4.5, 
      15, 
      true
    ),
(
      'stir-fried-nile-perch-with-rice-rc0vg', 
      'fish-dishes', 
      'Stir Fried Nile Perch with Rice', 
      'Stir fried Nile perch with rice.', 
      1110, 
      'https://loremflickr.com/400/300/stir%2Cfried%2Cnile%2Cperch%2Crice', 
      4.5, 
      15, 
      true
    );

INSERT INTO menu_items (id, category_id, name, description, price, image_url, rating, preparation_time, available) VALUES 
(
      'chilli-fish-1nxzz', 
      'fish-dishes', 
      'Chilli Fish', 
      'Fish with chilli sauce.', 
      1110, 
      'https://loremflickr.com/400/300/chilli%2Cfish', 
      4.5, 
      15, 
      true
    ),
(
      'fish-cutlet-zvgal', 
      'fish-dishes', 
      'Fish Cutlet', 
      'Fish cutlet.', 
      1350, 
      'https://loremflickr.com/400/300/fish%2Ccutlet', 
      4.5, 
      15, 
      true
    ),
(
      'fish-goulash-ik993', 
      'fish-dishes', 
      'Fish Goulash', 
      'Fish goulash.', 
      1400, 
      'https://loremflickr.com/400/300/fish%2Cgoulash', 
      4.5, 
      15, 
      true
    ),
(
      'poached-nile-perch-0ydlc', 
      'fish-dishes', 
      'Poached Nile Perch', 
      'Poached Nile perch.', 
      1400, 
      'https://loremflickr.com/400/300/poached%2Cnile%2Cperch', 
      4.5, 
      15, 
      true
    ),
(
      'club-sandwich-rajb1', 
      'sandwiches', 
      'Club Sandwich', 
      'Club sandwich.', 
      840, 
      'https://loremflickr.com/400/300/club%2Csandwich', 
      4.5, 
      15, 
      true
    ),
(
      'steak-sandwich-p9c83', 
      'sandwiches', 
      'Steak Sandwich', 
      'Steak sandwich.', 
      780, 
      'https://loremflickr.com/400/300/steak%2Csandwich', 
      4.5, 
      15, 
      true
    ),
(
      'steak-and-cheese-sandwich-548wl', 
      'sandwiches', 
      'Steak and Cheese Sandwich', 
      'Steak and cheese sandwich.', 
      720, 
      'https://loremflickr.com/400/300/steak%2Ccheese%2Csandwich', 
      4.5, 
      15, 
      true
    ),
(
      'grilled-ham-and-cheese-sandwich-414af', 
      'sandwiches', 
      'Grilled Ham and Cheese Sandwich', 
      'Grilled ham and cheese sandwich.', 
      740, 
      'https://loremflickr.com/400/300/grilled%2Cham%2Ccheese%2Csandwich', 
      4.5, 
      15, 
      true
    ),
(
      'fish-sandwich-v0qrj', 
      'sandwiches', 
      'Fish Sandwich', 
      'Fish sandwich.', 
      720, 
      'https://loremflickr.com/400/300/fish%2Csandwich', 
      4.5, 
      15, 
      true
    ),
(
      'tuna-sandwich-xjfer', 
      'sandwiches', 
      'Tuna Sandwich', 
      'Tuna sandwich.', 
      840, 
      'https://loremflickr.com/400/300/tuna%2Csandwich', 
      4.5, 
      15, 
      true
    ),
(
      'vegetable-sandwich-733tp', 
      'sandwiches', 
      'Vegetable Sandwich', 
      'Vegetable sandwich.', 
      800, 
      'https://loremflickr.com/400/300/vegetable%2Csandwich', 
      4.5, 
      15, 
      true
    ),
(
      'chicken-sandwich-qs47c', 
      'sandwiches', 
      'Chicken Sandwich', 
      'Chicken sandwich.', 
      720, 
      'https://loremflickr.com/400/300/chicken%2Csandwich', 
      4.5, 
      15, 
      true
    ),
(
      'cheese-burger-19rel', 
      'burgers', 
      'Cheese Burger', 
      'Cheese burger.', 
      800, 
      'https://loremflickr.com/400/300/cheese%2Cburger', 
      4.5, 
      15, 
      true
    ),
(
      'ham-cheese-burger-riq49', 
      'burgers', 
      'Ham & Cheese Burger', 
      'Ham and cheese burger.', 
      840, 
      'https://loremflickr.com/400/300/ham%2Ccheese%2Cburger', 
      4.5, 
      15, 
      true
    ),
(
      'egg-cheese-burger-cp9r4', 
      'burgers', 
      'Egg & Cheese Burger', 
      'Egg and cheese burger.', 
      740, 
      'https://loremflickr.com/400/300/egg%2Ccheese%2Cburger', 
      4.5, 
      15, 
      true
    ),
(
      'hamburger-w64tz', 
      'burgers', 
      'Hamburger', 
      'Hamburger.', 
      840, 
      'https://loremflickr.com/400/300/hamburger', 
      4.5, 
      15, 
      true
    ),
(
      'cheese-bacon-burger-d6k9n', 
      'burgers', 
      'Cheese & Bacon Burger', 
      'Cheese and bacon burger.', 
      840, 
      'https://loremflickr.com/400/300/cheese%2Cbacon%2Cburger', 
      4.5, 
      15, 
      true
    ),
(
      'pizza-quattro-formaggi-n4lm9', 
      'pizza', 
      'Pizza Quattro Formaggi', 
      'Red sauce, mozzarella, provolone, Gouda, and parmesan.', 
      1200, 
      'https://loremflickr.com/400/300/quattro%2Cformaggi%2Cpizza', 
      4.5, 
      15, 
      true
    ),
(
      'pizza-napoletana-ump09', 
      'pizza', 
      'Pizza Napoletana', 
      'Red sauce, mozzarella, anchovies, black olive, and capers.', 
      1200, 
      'https://loremflickr.com/400/300/napoletana%2Cpizza', 
      4.5, 
      15, 
      true
    ),
(
      'pizza-gorgonzola-red-y3abo', 
      'pizza', 
      'Pizza Gorgonzola Red', 
      'Red sauce, mozzarella, and blue cheese.', 
      1200, 
      'https://loremflickr.com/400/300/gorgonzola%2Cpizza%2Cred', 
      4.5, 
      15, 
      true
    ),
(
      'pizza-gorgonzola-white-mmlp8', 
      'pizza', 
      'Pizza Gorgonzola White', 
      'Mozzarella and blue cheese.', 
      1200, 
      'https://loremflickr.com/400/300/gorgonzola%2Cpizza%2Cwhite', 
      4.5, 
      15, 
      true
    ),
(
      'pizza-vegetarian-m0tx9', 
      'pizza', 
      'Pizza Vegetarian', 
      'Red sauce, mozzarella, and seasonal vegetables.', 
      990, 
      'https://loremflickr.com/400/300/vegetarian%2Cpizza', 
      4.5, 
      15, 
      true
    ),
(
      'pizza-spinach-eggplant-mwt96', 
      'pizza', 
      'Pizza Spinach & Eggplant', 
      'Red sauce, mozzarella, grilled eggplant, and spinach.', 
      990, 
      'https://loremflickr.com/400/300/spinach%2Ceggplant%2Cpizza', 
      4.5, 
      15, 
      true
    ),
(
      'pizza-quattro-stagioni-n9ob6', 
      'pizza', 
      'Pizza Quattro Stagioni', 
      'Red sauce, mozzarella, mushroom, olive, and tomato slice.', 
      1200, 
      'https://loremflickr.com/400/300/quattro%2Cstagioni%2Cpizza', 
      4.5, 
      15, 
      true
    ),
(
      'pizza-salami-8u31e', 
      'pizza', 
      'Pizza Salami', 
      'Red sauce, mozzarella, and salami.', 
      1200, 
      'https://loremflickr.com/400/300/salami%2Cpizza', 
      4.5, 
      15, 
      true
    ),
(
      'pizza-sausage-rxjh3', 
      'pizza', 
      'Pizza Sausage', 
      'Red sauce, grilled onion, mushroom, and sausage.', 
      1200, 
      'https://loremflickr.com/400/300/sausage%2Cpizza', 
      4.5, 
      15, 
      true
    ),
(
      'pizza-tuna-white-mo603', 
      'pizza', 
      'Pizza Tuna White', 
      'Mozzarella, tuna fish, and onion.', 
      1200, 
      'https://loremflickr.com/400/300/tuna%2Cpizza%2Cwhite', 
      4.5, 
      15, 
      true
    ),
(
      'pizza-tuna-red-pvdad', 
      'pizza', 
      'Pizza Tuna Red', 
      'Mozzarella, red sauce, tuna fish, and onion.', 
      1200, 
      'https://loremflickr.com/400/300/tuna%2Cpizza%2Cred', 
      4.5, 
      15, 
      true
    ),
(
      'pizza-with-grilled-chicken-4w80f', 
      'pizza', 
      'Pizza with Grilled Chicken', 
      'Red sauce, mozzarella, chicken breast, spinach, and goat cheese.', 
      1200, 
      'https://loremflickr.com/400/300/grilled%2Cchicken%2Cpizza', 
      4.5, 
      15, 
      true
    ),
(
      'pizza-hawaii-6pup2', 
      'pizza', 
      'Pizza Hawaii', 
      'Red sauce, mozzarella, pineapple, and ham.', 
      1200, 
      'https://loremflickr.com/400/300/hawaii%2Cpizza', 
      4.5, 
      15, 
      true
    ),
(
      'pizza-calzone-special-2o6e0', 
      'pizza', 
      'Pizza Calzone Special', 
      'Mozzarella, ham, and mushroom.', 
      1200, 
      'https://loremflickr.com/400/300/calzone%2Cpizza', 
      4.5, 
      15, 
      true
    ),
(
      'doro-firfir-je4ee', 
      'traditional-food', 
      'Doro Firfir', 
      'Traditional Ethiopian doro firfir.', 
      1380, 
      'https://loremflickr.com/400/300/doro%2Cfirfir', 
      4.5, 
      15, 
      true
    ),
(
      'tibs-9t86a', 
      'traditional-food', 
      'Tibs', 
      'Traditional Ethiopian tibs.', 
      1350, 
      'https://loremflickr.com/400/300/tibs', 
      4.5, 
      15, 
      true
    ),
(
      'tibs-firfir-zhhcr', 
      'traditional-food', 
      'Tibs Firfir', 
      'Traditional Ethiopian tibs firfir.', 
      1380, 
      'https://loremflickr.com/400/300/tibs%2Cfirfir', 
      4.5, 
      15, 
      true
    ),
(
      'quanta-firfir-ul5c9', 
      'traditional-food', 
      'Quanta Firfir', 
      'Traditional Ethiopian quanta firfir.', 
      1350, 
      'https://loremflickr.com/400/300/quanta%2Cfirfir', 
      4.5, 
      15, 
      true
    ),
(
      'kitfo-3iqf3', 
      'traditional-food', 
      'Kitfo', 
      'Traditional Ethiopian kitfo.', 
      1350, 
      'https://loremflickr.com/400/300/kitfo', 
      4.5, 
      15, 
      true
    ),
(
      'tegabino-pob6s', 
      'traditional-food', 
      'Tegabino', 
      'Traditional Ethiopian tegabino.', 
      970, 
      'https://loremflickr.com/400/300/tegabino', 
      4.5, 
      15, 
      true
    ),
(
      'bozena-mdcju', 
      'traditional-food', 
      'Bozena', 
      'Traditional Ethiopian bozena.', 
      1110, 
      'https://loremflickr.com/400/300/bozena', 
      4.5, 
      15, 
      true
    ),
(
      'yetsome-firfir-feksw', 
      'traditional-food', 
      'Yetsome Firfir', 
      'Traditional Ethiopian yetsome firfir.', 
      970, 
      'https://loremflickr.com/400/300/yetsome%2Cfirfir', 
      4.5, 
      15, 
      true
    ),
(
      'tuna-firfir-0oed9', 
      'traditional-food', 
      'Tuna Firfir', 
      'Traditional Ethiopian tuna firfir.', 
      1110, 
      'https://loremflickr.com/400/300/tuna%2Cfirfir', 
      4.5, 
      15, 
      true
    ),
(
      'cream-caramel-with-ice-cream-8v9t5', 
      'desserts', 
      'Cream Caramel with Ice Cream', 
      'Cream caramel served with ice cream.', 
      250, 
      'https://loremflickr.com/400/300/cream%2Ccaramel%2Cice%2Ccream', 
      4.5, 
      15, 
      true
    ),
(
      'fruit-salad-with-ice-cream-3bvj9', 
      'desserts', 
      'Fruit Salad with Ice Cream', 
      'Fresh fruit salad served with ice cream.', 
      250, 
      'https://loremflickr.com/400/300/fruit%2Csalad%2Cice%2Ccream', 
      4.5, 
      15, 
      true
    ),
(
      'fruit-salad-z9muk', 
      'desserts', 
      'Fruit Salad', 
      'Fresh fruit salad.', 
      250, 
      'https://loremflickr.com/400/300/fruit%2Csalad', 
      4.5, 
      15, 
      true
    ),
(
      'crepes-mixed-fruit-ghgb2', 
      'desserts', 
      'Crepes Mixed Fruit', 
      'Crepes with mixed fruit.', 
      260, 
      'https://loremflickr.com/400/300/crepes%2Cmixed%2Cfruit', 
      4.5, 
      15, 
      true
    ),
(
      'crepes-rodeo-0cjo9', 
      'desserts', 
      'Crepes Rodeo', 
      'Chocolate, banana, and ice cream crepes.', 
      260, 
      'https://loremflickr.com/400/300/crepes%2Crodeo', 
      4.5, 
      15, 
      true
    ),
(
      'crepes-cognac-44i6c', 
      'desserts', 
      'Crepes Cognac', 
      'Oranges, cognac, and sugar crepes.', 
      202, 
      'https://loremflickr.com/400/300/crepes%2Ccognac', 
      4.5, 
      15, 
      true
    ),
(
      'affogato-with-coffee-d3297', 
      'desserts', 
      'Affogato with Coffee', 
      'Affogato served with coffee.', 
      260, 
      'https://loremflickr.com/400/300/affogato%2Ccoffee', 
      4.5, 
      15, 
      true
    ),
(
      'mix-cup-rdjeo', 
      'desserts', 
      'Mix Cup', 
      'Three scoops of ice cream.', 
      265, 
      'https://loremflickr.com/400/300/ice%2Ccream%2Cmix%2Ccup', 
      4.5, 
      15, 
      true
    ),
(
      'spring-cup-08r6i', 
      'desserts', 
      'Spring Cup', 
      'Strawberry ice, vanilla ice, watermelon, pineapple, and fresh cream.', 
      260, 
      'https://loremflickr.com/400/300/spring%2Ccup%2Cdessert', 
      4.5, 
      15, 
      true
    ),
(
      'amaretto-r9jv5', 
      'desserts', 
      'Amaretto', 
      'Ice cream, amaretto liquor, and biscuit.', 
      453, 
      'https://loremflickr.com/400/300/amaretto%2Cdessert', 
      4.5, 
      15, 
      true
    );

INSERT INTO menu_items (id, category_id, name, description, price, image_url, rating, preparation_time, available) VALUES 
(
      'rodeo-cup-t2edk', 
      'desserts', 
      'Rodeo Cup', 
      'Mix ice cream, fresh cream, and noccioloni topping.', 
      260, 
      'https://loremflickr.com/400/300/rodeo%2Ccup%2Cdessert', 
      4.5, 
      15, 
      true
    ),
(
      'special-mixed-grilled-etyxe', 
      'day-special-menu', 
      'Special Mixed Grilled', 
      'Special mixed grilled meats.', 
      1400, 
      'https://loremflickr.com/400/300/mixed%2Cgrilled', 
      4.5, 
      15, 
      true
    ),
(
      'special-hot-canape-rw092', 
      'day-special-menu', 
      'Special Hot Canape', 
      'Special hot canape.', 
      1400, 
      'https://loremflickr.com/400/300/hot%2Ccanape', 
      4.5, 
      15, 
      true
    ),
(
      'special-grilled-nile-perch-5ooav', 
      'day-special-menu', 
      'Special Grilled Nile Perch', 
      'Special grilled Nile perch.', 
      1400, 
      'https://loremflickr.com/400/300/grilled%2Cnile%2Cperch%2Cspecial', 
      4.5, 
      15, 
      true
    ),
(
      'chicken-wing-buffalo-y5wz0', 
      'day-special-menu', 
      'Chicken Wing Buffalo', 
      'Buffalo style chicken wings.', 
      1300, 
      'https://loremflickr.com/400/300/buffalo%2Cchicken%2Cwings', 
      4.5, 
      15, 
      true
    ),
(
      'special-cow-boy-steak-2f9m4', 
      'day-special-menu', 
      'Special Cow Boy Steak', 
      'Special cowboy steak.', 
      1350, 
      'https://loremflickr.com/400/300/cowboy%2Csteak', 
      4.5, 
      15, 
      true
    ),
(
      'special-steak-diana-h8w93', 
      'day-special-menu', 
      'Special Steak Diana', 
      'Special steak Diana.', 
      1350, 
      'https://loremflickr.com/400/300/steak%2Cdiana', 
      4.5, 
      15, 
      true
    ),
(
      'steak-albismark-1e96q', 
      'day-special-menu', 
      'Steak Albismark', 
      'Steak Albismark.', 
      1350, 
      'https://loremflickr.com/400/300/steak%2Calbismark', 
      4.5, 
      15, 
      true
    ),
(
      'special-pizza-yyz7s', 
      'day-special-menu', 
      'Special Pizza', 
      'Special pizza.', 
      1350, 
      'https://loremflickr.com/400/300/special%2Cpizza', 
      4.5, 
      15, 
      true
    ),
(
      'fried-whole-jumbo-fish-kbju0', 
      'day-special-menu', 
      'Fried Whole Jumbo Fish', 
      'Fried whole jumbo fish.', 
      1350, 
      'https://loremflickr.com/400/300/fried%2Cjumbo%2Cfish', 
      4.5, 
      15, 
      true
    ),
(
      'assorted-bbq-x7ur4', 
      'day-special-menu', 
      'Assorted BBQ', 
      'Assorted BBQ meats.', 
      1400, 
      'https://loremflickr.com/400/300/assorted%2Cbbq', 
      4.5, 
      15, 
      true
    ),
(
      'beef-bbq-27xs4', 
      'day-special-menu', 
      'Beef BBQ', 
      'Beef BBQ.', 
      1400, 
      'https://loremflickr.com/400/300/beef%2Cbbq', 
      4.5, 
      15, 
      true
    ),
(
      'chicken-bbq-aupaf', 
      'day-special-menu', 
      'Chicken BBQ', 
      'Chicken BBQ.', 
      1400, 
      'https://loremflickr.com/400/300/chicken%2Cbbq', 
      4.5, 
      15, 
      true
    ),
(
      'fish-bbq-azxtr', 
      'day-special-menu', 
      'Fish BBQ', 
      'Fish BBQ.', 
      1400, 
      'https://loremflickr.com/400/300/fish%2Cbbq', 
      4.5, 
      15, 
      true
    ),
(
      'lamb-bbq-pgp5w', 
      'day-special-menu', 
      'Lamb BBQ', 
      'Lamb BBQ.', 
      1400, 
      'https://loremflickr.com/400/300/lamb%2Cbbq', 
      4.5, 
      15, 
      true
    ),
(
      'special-beef-cutlet-xh00l', 
      'day-special-menu', 
      'Special Beef Cutlet', 
      'Special beef cutlet.', 
      1350, 
      'https://loremflickr.com/400/300/beef%2Ccutlet%2Cspecial', 
      4.5, 
      15, 
      true
    ),
(
      'argentina-combo-vip-x78kg', 
      'day-special-menu', 
      'Argentina Combo VIP', 
      'Argentina combo VIP.', 
      1400, 
      'https://loremflickr.com/400/300/argentina%2Ccombo%2Cvip', 
      4.5, 
      15, 
      true
    ),
(
      'french-service-bvfdg', 
      'day-special-menu', 
      'French Service', 
      'French service special.', 
      2850, 
      'https://loremflickr.com/400/300/french%2Cservice', 
      4.5, 
      15, 
      true
    ),
(
      'rodeo-classic-2vc8l', 
      'day-special-menu', 
      'Rodeo Classic', 
      'Rodeo classic special.', 
      1800, 
      'https://loremflickr.com/400/300/rodeo%2Cclassic', 
      4.5, 
      15, 
      true
    ),
(
      'special-lamb-tibs-83cyz', 
      'day-special-traditional-food', 
      'Special Lamb Tibs', 
      'Special lamb tibs.', 
      1350, 
      'https://loremflickr.com/400/300/lamb%2Ctibs%2Cspecial', 
      4.5, 
      15, 
      true
    ),
(
      'traditional-rodeo-classic-36t8v', 
      'day-special-traditional-food', 
      'Traditional Rodeo Classic', 
      'Traditional Rodeo classic.', 
      1350, 
      'https://loremflickr.com/400/300/traditional%2Crodeo%2Cclassic', 
      4.5, 
      15, 
      true
    ),
(
      'special-doro-watt-m95qm', 
      'day-special-traditional-food', 
      'Special Doro Watt', 
      'Special doro watt.', 
      1380, 
      'https://loremflickr.com/400/300/doro%2Cwatt%2Cspecial', 
      4.5, 
      15, 
      true
    ),
(
      'special-mix-tibs-3xmpc', 
      'day-special-traditional-food', 
      'Special Mix Tibs', 
      'Special mix tibs.', 
      1380, 
      'https://loremflickr.com/400/300/mix%2Ctibs%2Cspecial', 
      4.5, 
      15, 
      true
    ),
(
      'steak-goulash-egwj7', 
      'day-special-traditional-food', 
      'Steak Goulash', 
      'Steak goulash.', 
      1350, 
      'https://loremflickr.com/400/300/steak%2Cgoulash', 
      4.5, 
      15, 
      true
    ),
(
      'special-fish-goulash-6lc4l', 
      'day-special-traditional-food', 
      'Special Fish Goulash', 
      'Special fish goulash.', 
      1350, 
      'https://loremflickr.com/400/300/fish%2Cgoulash%2Cspecial', 
      4.5, 
      15, 
      true
    ),
(
      'fish-kitfo-59eq5', 
      'day-special-traditional-food', 
      'Fish Kitfo', 
      'Fish kitfo.', 
      1350, 
      'https://loremflickr.com/400/300/fish%2Ckitfo', 
      4.5, 
      15, 
      true
    ),
(
      'tea-3of2r', 
      'hot-drinks', 
      'Tea', 
      'Hot tea.', 
      50, 
      'https://loremflickr.com/400/300/tea', 
      4.5, 
      15, 
      true
    ),
(
      'coffee-0j27w', 
      'hot-drinks', 
      'Coffee', 
      'Hot coffee.', 
      67, 
      'https://loremflickr.com/400/300/coffee', 
      4.5, 
      15, 
      true
    ),
(
      'macchiato-h3sns', 
      'hot-drinks', 
      'Macchiato', 
      'Coffee macchiato.', 
      70, 
      'https://loremflickr.com/400/300/macchiato', 
      4.5, 
      15, 
      true
    ),
(
      'coffee-with-milk-mzti0', 
      'hot-drinks', 
      'Coffee with Milk', 
      'Coffee with milk.', 
      101, 
      'https://loremflickr.com/400/300/coffee%2Cmilk', 
      4.5, 
      15, 
      true
    ),
(
      'cappuccino-pw0q1', 
      'hot-drinks', 
      'Cappuccino', 
      'Cappuccino.', 
      120, 
      'https://loremflickr.com/400/300/cappuccino', 
      4.5, 
      15, 
      true
    ),
(
      'orange-juice-1l0ud', 
      'juices', 
      'Orange Juice', 
      'Fresh orange juice.', 
      160, 
      'https://loremflickr.com/400/300/orange%2Cjuice', 
      4.5, 
      15, 
      true
    ),
(
      'tin-juice-km1qh', 
      'juices', 
      'Tin Juice', 
      'Tin juice.', 
      150, 
      'https://loremflickr.com/400/300/tin%2Cjuice', 
      4.5, 
      15, 
      true
    ),
(
      'red-bull-w9i53', 
      'cold-drinks', 
      'Red Bull', 
      'Red Bull energy drink.', 
      250, 
      'https://loremflickr.com/400/300/red%2Cbull', 
      4.5, 
      15, 
      true
    ),
(
      'soft-drink-st9n5', 
      'cold-drinks', 
      'Soft Drink', 
      'Soft drink.', 
      60, 
      'https://loremflickr.com/400/300/soft%2Cdrink', 
      4.5, 
      15, 
      true
    ),
(
      'spring-water-sdv7v', 
      'cold-drinks', 
      'Spring Water', 
      'Spring water.', 
      60, 
      'https://loremflickr.com/400/300/spring%2Cwater', 
      4.5, 
      15, 
      true
    ),
(
      'ambo-src2c', 
      'cold-drinks', 
      'Ambo', 
      'Ambo mineral water.', 
      60, 
      'https://loremflickr.com/400/300/ambo%2Cwater', 
      4.5, 
      15, 
      true
    ),
(
      'royal-tonic-ssuky', 
      'cold-drinks', 
      'Royal Tonic', 
      'Royal tonic water.', 
      65, 
      'https://loremflickr.com/400/300/royal%2Ctonic', 
      4.5, 
      15, 
      true
    ),
(
      'castel-beer-1ntg8', 
      'beer', 
      'Castel Beer', 
      'Castel beer.', 
      67, 
      'https://loremflickr.com/400/300/castel%2Cbeer', 
      4.5, 
      15, 
      true
    ),
(
      'st-george-beer-as2id', 
      'beer', 
      'St. George Beer', 
      'St. George beer.', 
      67, 
      'https://loremflickr.com/400/300/st%2Cgeorge%2Cbeer', 
      4.5, 
      15, 
      true
    ),
(
      'bati-beer-fzf4c', 
      'beer', 
      'Bati Beer', 
      'Bati beer.', 
      67, 
      'https://loremflickr.com/400/300/bati%2Cbeer', 
      4.5, 
      15, 
      true
    ),
(
      'dashen-beer-knzb8', 
      'beer', 
      'Dashen Beer', 
      'Dashen beer.', 
      67, 
      'https://loremflickr.com/400/300/dashen%2Cbeer', 
      4.5, 
      15, 
      true
    ),
(
      'harar-beer-aj55q', 
      'beer', 
      'Harar Beer', 
      'Harar beer.', 
      67, 
      'https://loremflickr.com/400/300/harar%2Cbeer', 
      4.5, 
      15, 
      true
    ),
(
      'bedele-beer-2n5g8', 
      'beer', 
      'Bedele Beer', 
      'Bedele beer.', 
      67, 
      'https://loremflickr.com/400/300/bedele%2Cbeer', 
      4.5, 
      15, 
      true
    ),
(
      'bedele-special-beer-1y00d', 
      'beer', 
      'Bedele Special Beer', 
      'Bedele special beer.', 
      85, 
      'https://loremflickr.com/400/300/bedele%2Cspecial%2Cbeer', 
      4.5, 
      15, 
      true
    ),
(
      'meta-beer-thivf', 
      'beer', 
      'Meta Beer', 
      'Meta beer.', 
      67, 
      'https://loremflickr.com/400/300/meta%2Cbeer', 
      4.5, 
      15, 
      true
    ),
(
      'imported-beer-ni8u9', 
      'beer', 
      'Imported Beer', 
      'Imported beer.', 
      80, 
      'https://loremflickr.com/400/300/imported%2Cbeer', 
      4.5, 
      15, 
      true
    ),
(
      'local-wine-ygd3d', 
      'wine', 
      'Local Wine', 
      'Local wine.', 
      900, 
      'https://loremflickr.com/400/300/local%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'imported-wine-small-2mmor', 
      'wine', 
      'Imported Wine Small', 
      'Imported wine small bottle.', 
      1999, 
      'https://loremflickr.com/400/300/imported%2Cwine%2Csmall', 
      4.5, 
      15, 
      true
    ),
(
      'glass-of-wine-red-0qy6d', 
      'wine', 
      'Glass of Wine Red', 
      'Glass of red wine.', 
      273, 
      'https://loremflickr.com/400/300/red%2Cwine%2Cglass', 
      4.5, 
      15, 
      true
    );

INSERT INTO menu_items (id, category_id, name, description, price, image_url, rating, preparation_time, available) VALUES 
(
      'glass-of-wine-white-hrixa', 
      'wine', 
      'Glass of Wine White', 
      'Glass of white wine.', 
      273, 
      'https://loremflickr.com/400/300/white%2Cwine%2Cglass', 
      4.5, 
      15, 
      true
    ),
(
      'champagne-local-fvxp0', 
      'wine', 
      'Champagne Local', 
      'Local champagne.', 
      3500, 
      'https://loremflickr.com/400/300/local%2Cchampagne', 
      4.5, 
      15, 
      true
    ),
(
      'champagne-imported-ohacb', 
      'wine', 
      'Champagne Imported', 
      'Imported champagne.', 
      11900, 
      'https://loremflickr.com/400/300/imported%2Cchampagne', 
      4.5, 
      15, 
      true
    ),
(
      'acacia-dry-red-311dc', 
      'wine', 
      'Acacia Dry Red', 
      'A deep ruby red color with warm spicy notes.', 
      2000, 
      'https://loremflickr.com/400/300/acacia%2Cdry%2Cred%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'acacia-medium-sweet-red-65ecj', 
      'wine', 
      'Acacia Medium Sweet Red', 
      'Fruity notes with a touch of sweetness.', 
      2000, 
      'https://loremflickr.com/400/300/acacia%2Csweet%2Cred%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'acacia-medium-sweet-white-0q8bz', 
      'wine', 
      'Acacia Medium Sweet White', 
      'Golden white color wine with aromas of peach and slight hint of sweetness.', 
      2000, 
      'https://loremflickr.com/400/300/acacia%2Csweet%2Cwhite%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'rift-valley-chardonnay-x7t3o', 
      'wine', 
      'Rift Valley Chardonnay', 
      'White wine with golden color, flavors of peach and apricot, crisp and refreshing with honey aromas.', 
      2100, 
      'https://loremflickr.com/400/300/rift%2Cvalley%2Cchardonnay', 
      4.5, 
      15, 
      true
    ),
(
      'rift-valley-cabernet-sauvignon-f04av', 
      'wine', 
      'Rift Valley Cabernet Sauvignon', 
      'Brilliant deep red color, intense aromas of green pepper and mixed spices with supple body.', 
      2100, 
      'https://loremflickr.com/400/300/rift%2Cvalley%2Ccabernet%2Csauvignon', 
      4.5, 
      15, 
      true
    ),
(
      'rift-valley-merlot-dgd86', 
      'wine', 
      'Rift Valley Merlot', 
      'Deep red color with intense aromas of fruits and spices.', 
      2100, 
      'https://loremflickr.com/400/300/rift%2Cvalley%2Cmerlot', 
      4.5, 
      15, 
      true
    ),
(
      'rift-valley-syrah-yehh2', 
      'wine', 
      'Rift Valley Syrah', 
      'Full bodied ruby red wine with rounded palate and slight notes of dark roasted coffee.', 
      2100, 
      'https://loremflickr.com/400/300/rift%2Cvalley%2Csyrah', 
      4.5, 
      15, 
      true
    ),
(
      'swart-land-8giiu', 
      'imported-wine', 
      'Swart Land', 
      'South African white/red wine.', 
      6000, 
      'https://loremflickr.com/400/300/swart%2Cland%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'drostdy-hof-vs9y9', 
      'imported-wine', 
      'Drostdy Hof', 
      'South African white/red wine.', 
      6000, 
      'https://loremflickr.com/400/300/drostdy%2Chof%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'libertas-37v1b', 
      'imported-wine', 
      'Libertas', 
      'South African white/red wine.', 
      6000, 
      'https://loremflickr.com/400/300/libertas%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'cellar-cask-lvfui', 
      'imported-wine', 
      'Cellar Cask', 
      'South African white wine.', 
      6000, 
      'https://loremflickr.com/400/300/cellar%2Ccask%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'cast-in-stone-pvc5t', 
      'imported-wine', 
      'Cast in Stone', 
      'South African red wine.', 
      6000, 
      'https://loremflickr.com/400/300/cast%2Cin%2Cstone%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'south-south-west-ugo71', 
      'imported-wine', 
      'South South West', 
      'South African white/red wine.', 
      6000, 
      'https://loremflickr.com/400/300/south%2Csouth%2Cwest%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'craichall-98y54', 
      'imported-wine', 
      'Craichall', 
      'French white wine.', 
      6000, 
      'https://loremflickr.com/400/300/craichall%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'dieux-papes-9vyra', 
      'imported-wine', 
      'Dieux Papes', 
      'Italian red wine.', 
      6000, 
      'https://loremflickr.com/400/300/dieux%2Cpapes%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'ruffino-oqviy', 
      'imported-wine', 
      'Ruffino', 
      'Italian white/red wine.', 
      6000, 
      'https://loremflickr.com/400/300/ruffino%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'terre-all-lage-a1no6', 
      'imported-wine', 
      'Terre all Lage', 
      'French red wine.', 
      6000, 
      'https://loremflickr.com/400/300/terre%2Call%2Clage%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'saint-chinian-xgi9o', 
      'imported-wine', 
      'Saint Chinian', 
      'French red wine.', 
      6000, 
      'https://loremflickr.com/400/300/saint%2Cchinian%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'domaine-larroave-rj88s', 
      'imported-wine', 
      'Domaine Larroave', 
      'French red wine.', 
      6000, 
      'https://loremflickr.com/400/300/domaine%2Clarroave%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'gamay-fo5kh', 
      'imported-wine', 
      'Gamay', 
      'Indian red wine.', 
      6000, 
      'https://loremflickr.com/400/300/gamay%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'riviera-6zvih', 
      'imported-wine', 
      'Riviera', 
      'French red wine.', 
      6000, 
      'https://loremflickr.com/400/300/riviera%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'chastenet-hcpp6', 
      'imported-wine', 
      'Chastenet', 
      'Italian red wine.', 
      6000, 
      'https://loremflickr.com/400/300/chastenet%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'bodie-jrmz6', 
      'imported-wine', 
      'Bodie', 
      'Italian red wine.', 
      6000, 
      'https://loremflickr.com/400/300/bodie%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'merlot-vento-gr09j', 
      'imported-wine', 
      'Merlot Vento', 
      'Italian red wine.', 
      6000, 
      'https://loremflickr.com/400/300/merlot%2Cvento%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'cabernet-vento-y1ypf', 
      'imported-wine', 
      'Cabernet Vento', 
      'Italian red wine.', 
      6000, 
      'https://loremflickr.com/400/300/cabernet%2Cvento%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'bardolino-8sq1w', 
      'imported-wine', 
      'Bardolino', 
      'Italian red wine.', 
      6000, 
      'https://loremflickr.com/400/300/bardolino%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'chianti-lcvwk', 
      'imported-wine', 
      'Chianti', 
      'Italian red wine.', 
      6000, 
      'https://loremflickr.com/400/300/chianti%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'offley-port-a3qvh', 
      'imported-wine', 
      'Offley Port', 
      'Portuguese red wine.', 
      6000, 
      'https://loremflickr.com/400/300/offley%2Cport%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'valpolicella-f4xm3', 
      'imported-wine', 
      'Valpolicella', 
      'Italian red wine.', 
      6000, 
      'https://loremflickr.com/400/300/valpolicella%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'paul-valmeras-lj5pm', 
      'imported-wine', 
      'Paul Valmeras', 
      'French red wine.', 
      6000, 
      'https://loremflickr.com/400/300/paul%2Cvalmeras%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'piat-d-or-8ljg0', 
      'imported-wine', 
      'Piat d''Or', 
      'French white/red wine.', 
      6000, 
      'https://loremflickr.com/400/300/piat%2Cdor%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'leziria-4328b', 
      'imported-wine', 
      'Leziria', 
      'Portuguese red wine.', 
      6000, 
      'https://loremflickr.com/400/300/leziria%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'boulaouane-yw85f', 
      'imported-wine', 
      'Boulaouane', 
      'French red wine.', 
      6000, 
      'https://loremflickr.com/400/300/boulaouane%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'beauchais-1tuv8', 
      'imported-wine', 
      'Beauchais', 
      'French red wine.', 
      6000, 
      'https://loremflickr.com/400/300/beauchais%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'amarone-della-valpolicella-mx0lm', 
      'imported-wine', 
      'Amarone della Valpolicella', 
      'French red wine.', 
      6000, 
      'https://loremflickr.com/400/300/amarone%2Cvalpolicella', 
      4.5, 
      15, 
      true
    ),
(
      'frascati-ho82r', 
      'imported-wine', 
      'Frascati', 
      'Italian white wine.', 
      6000, 
      'https://loremflickr.com/400/300/frascati%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'bianco-di-custoza-efwtw', 
      'imported-wine', 
      'Bianco di Custoza', 
      'Italian white wine.', 
      6000, 
      'https://loremflickr.com/400/300/bianco%2Ccustoza%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'soave-biqfh', 
      'imported-wine', 
      'Soave', 
      'Italian white wine.', 
      6000, 
      'https://loremflickr.com/400/300/soave%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'soave-classico-h4g9q', 
      'imported-wine', 
      'Soave Classico', 
      'Italian white wine.', 
      6000, 
      'https://loremflickr.com/400/300/soave%2Cclassico%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'bianco-vento-378mh', 
      'imported-wine', 
      'Bianco Vento', 
      'Italian white wine.', 
      6000, 
      'https://loremflickr.com/400/300/bianco%2Cvento%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'perlit-kf3fi', 
      'imported-wine', 
      'Perlit', 
      'Italian white wine.', 
      6000, 
      'https://loremflickr.com/400/300/perlit%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'castel-jkub3', 
      'imported-wine', 
      'Castel', 
      'French white wine.', 
      6000, 
      'https://loremflickr.com/400/300/castel%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'partager-34jwq', 
      'imported-wine', 
      'Partager', 
      'French white wine.', 
      6000, 
      'https://loremflickr.com/400/300/partager%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'blancs-deblaacs-57yao', 
      'imported-wine', 
      'Blancs Deblaacs', 
      'French white wine.', 
      6000, 
      'https://loremflickr.com/400/300/blancs%2Cdeblaacs%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'axumite-pi1jm', 
      'local-wine-big', 
      'Axumite', 
      'Local wine big bottle.', 
      6000, 
      'https://loremflickr.com/400/300/axumite%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'gouder-ys383', 
      'local-wine-big', 
      'Gouder', 
      'Local wine big bottle.', 
      6000, 
      'https://loremflickr.com/400/300/gouder%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'kamila-kae50', 
      'local-wine-big', 
      'Kamila', 
      'Local wine big bottle.', 
      6000, 
      'https://loremflickr.com/400/300/kamila%2Cwine', 
      4.5, 
      15, 
      true
    );

INSERT INTO menu_items (id, category_id, name, description, price, image_url, rating, preparation_time, available) VALUES 
(
      'awash-cristal-njewn', 
      'local-wine-big', 
      'Awash Cristal', 
      'Local wine big bottle.', 
      6000, 
      'https://loremflickr.com/400/300/awash%2Ccristal%2Cwine', 
      4.5, 
      15, 
      true
    ),
(
      'courvoisier-vsop-4k4cb', 
      'cognac', 
      'Courvoisier VSOP', 
      'Courvoisier VSOP cognac.', 
      660, 
      'https://loremflickr.com/400/300/courvoisier%2Cvsop', 
      4.5, 
      15, 
      true
    ),
(
      'courvoisier-f5u2g', 
      'cognac', 
      'Courvoisier', 
      'Courvoisier cognac.', 
      499, 
      'https://loremflickr.com/400/300/courvoisier', 
      4.5, 
      15, 
      true
    ),
(
      'hennessy-q7vjo', 
      'cognac', 
      'Hennessy', 
      'Hennessy cognac.', 
      499, 
      'https://loremflickr.com/400/300/hennessy', 
      4.5, 
      15, 
      true
    ),
(
      'remy-martin-b2icf', 
      'cognac', 
      'Remy Martin', 
      'Remy Martin cognac.', 
      13799, 
      'https://loremflickr.com/400/300/remy%2Cmartin', 
      4.5, 
      15, 
      true
    ),
(
      'courvoisier-xo-mps6f', 
      'cognac', 
      'Courvoisier XO', 
      'Courvoisier XO cognac.', 
      13999, 
      'https://loremflickr.com/400/300/courvoisier%2Cxo', 
      4.5, 
      15, 
      true
    ),
(
      'hennessy-xo-kqsb3', 
      'cognac', 
      'Hennessy XO', 
      'Hennessy XO cognac.', 
      47000, 
      'https://loremflickr.com/400/300/hennessy%2Cxo', 
      4.5, 
      15, 
      true
    ),
(
      'remy-martin-xo-0qo08', 
      'cognac', 
      'Remy Martin XO', 
      'Remy Martin XO cognac.', 
      97000, 
      'https://loremflickr.com/400/300/remy%2Cmartin%2Cxo', 
      4.5, 
      15, 
      true
    ),
(
      'baileys-wz89p', 
      'liquor', 
      'Baileys', 
      'Baileys Irish cream.', 
      407, 
      'https://loremflickr.com/400/300/baileys', 
      4.5, 
      15, 
      true
    ),
(
      'sambuca-rahmr', 
      'liquor', 
      'Sambuca', 
      'Sambuca liqueur.', 
      407, 
      'https://loremflickr.com/400/300/sambuca', 
      4.5, 
      15, 
      true
    ),
(
      'coffee-cream-0u4gg', 
      'liquor', 
      'Coffee Cream', 
      'Coffee cream liqueur.', 
      407, 
      'https://loremflickr.com/400/300/coffee%2Ccream%2Cliqueur', 
      4.5, 
      15, 
      true
    ),
(
      'drambuie-5i7y4', 
      'liquor', 
      'Drambuie', 
      'Drambuie liqueur.', 
      407, 
      'https://loremflickr.com/400/300/drambuie', 
      4.5, 
      15, 
      true
    ),
(
      'tia-maria-nfnda', 
      'liquor', 
      'Tia Maria', 
      'Tia Maria liqueur.', 
      407, 
      'https://loremflickr.com/400/300/tia%2Cmaria', 
      4.5, 
      15, 
      true
    ),
(
      'creme-de-menthe-d34k1', 
      'liquor', 
      'Creme de Menthe', 
      'Creme de menthe liqueur.', 
      407, 
      'https://loremflickr.com/400/300/creme%2Cde%2Cmenthe', 
      4.5, 
      15, 
      true
    ),
(
      'malibu-3nwve', 
      'liquor', 
      'Malibu', 
      'Malibu coconut rum.', 
      407, 
      'https://loremflickr.com/400/300/malibu', 
      4.5, 
      15, 
      true
    ),
(
      'cointreau-qq2ag', 
      'liquor', 
      'Cointreau', 
      'Cointreau orange liqueur.', 
      407, 
      'https://loremflickr.com/400/300/cointreau', 
      4.5, 
      15, 
      true
    ),
(
      'martini-rq6dq', 
      'liquor', 
      'Martini', 
      'Martini vermouth.', 
      379, 
      'https://loremflickr.com/400/300/martini', 
      4.5, 
      15, 
      true
    ),
(
      'cinzano-yr0dc', 
      'liquor', 
      'Cinzano', 
      'Cinzano vermouth.', 
      407, 
      'https://loremflickr.com/400/300/cinzano', 
      4.5, 
      15, 
      true
    ),
(
      'ouzo-4da0q', 
      'liquor', 
      'Ouzo', 
      'Ouzo anise liqueur.', 
      407, 
      'https://loremflickr.com/400/300/ouzo', 
      4.5, 
      15, 
      true
    ),
(
      'pastis-51-hroj5', 
      'liquor', 
      'Pastis 51', 
      'Pastis 51 anise liqueur.', 
      407, 
      'https://loremflickr.com/400/300/pastis%2C51', 
      4.5, 
      15, 
      true
    ),
(
      'fernet-branca-gkv5i', 
      'liquor', 
      'Fernet Branca', 
      'Fernet Branca bitter.', 
      407, 
      'https://loremflickr.com/400/300/fernet%2Cbranca', 
      4.5, 
      15, 
      true
    ),
(
      'pernod-0wc73', 
      'liquor', 
      'Pernod', 
      'Pernod anise liqueur.', 
      407, 
      'https://loremflickr.com/400/300/pernod', 
      4.5, 
      15, 
      true
    ),
(
      'campari-bitter-10wv1', 
      'liquor', 
      'Campari Bitter', 
      'Campari bitter.', 
      207, 
      'https://loremflickr.com/400/300/campari%2Cbitter', 
      4.5, 
      15, 
      true
    ),
(
      'aperitif-8b7ut', 
      'liquor', 
      'Aperitif', 
      'Aperitif.', 
      399, 
      'https://loremflickr.com/400/300/aperitif', 
      4.5, 
      15, 
      true
    ),
(
      'chivas-regal-oz0n8', 
      'premium-whisky', 
      'Chivas Regal', 
      'Chivas Regal whisky.', 
      336, 
      'https://loremflickr.com/400/300/chivas%2Cregal', 
      4.5, 
      15, 
      true
    ),
(
      'chivas-regal-12-years-xxm9d', 
      'premium-whisky', 
      'Chivas Regal 12 Years', 
      'Chivas Regal 12 years whisky.', 
      336, 
      'https://loremflickr.com/400/300/chivas%2Cregal%2C12%2Cyears', 
      4.5, 
      15, 
      true
    ),
(
      'chivas-regal-18-years-aqhej', 
      'premium-whisky', 
      'Chivas Regal 18 Years', 
      'Chivas Regal 18 years whisky.', 
      720, 
      'https://loremflickr.com/400/300/chivas%2Cregal%2C18%2Cyears', 
      4.5, 
      15, 
      true
    ),
(
      'gold-label-jo94x', 
      'premium-whisky', 
      'Gold Label', 
      'Johnnie Walker Gold Label whisky.', 
      445, 
      'https://loremflickr.com/400/300/gold%2Clabel%2Cwhisky', 
      4.5, 
      15, 
      true
    ),
(
      'blue-label-jof1z', 
      'premium-whisky', 
      'Blue Label', 
      'Johnnie Walker Blue Label whisky.', 
      1250, 
      'https://loremflickr.com/400/300/blue%2Clabel%2Cwhisky', 
      4.5, 
      15, 
      true
    ),
(
      'green-label-25a3k', 
      'premium-whisky', 
      'Green Label', 
      'Johnnie Walker Green Label whisky.', 
      445, 
      'https://loremflickr.com/400/300/green%2Clabel%2Cwhisky', 
      4.5, 
      15, 
      true
    ),
(
      'black-label-uaw6n', 
      'premium-whisky', 
      'Black Label', 
      'Johnnie Walker Black Label whisky.', 
      295, 
      'https://loremflickr.com/400/300/black%2Clabel%2Cwhisky', 
      4.5, 
      15, 
      true
    ),
(
      'white-horse-4q3r1', 
      'regular-whisky', 
      'White Horse', 
      'White Horse whisky.', 
      290, 
      'https://loremflickr.com/400/300/white%2Chorse%2Cwhisky', 
      4.5, 
      15, 
      true
    ),
(
      'red-label-d57of', 
      'regular-whisky', 
      'Red Label', 
      'Johnnie Walker Red Label whisky.', 
      290, 
      'https://loremflickr.com/400/300/red%2Clabel%2Cwhisky', 
      4.5, 
      15, 
      true
    ),
(
      'highland-queen-17qz8', 
      'regular-whisky', 
      'Highland Queen', 
      'Highland Queen whisky.', 
      290, 
      'https://loremflickr.com/400/300/highland%2Cqueen%2Cwhisky', 
      4.5, 
      15, 
      true
    ),
(
      'grants-82pg0', 
      'regular-whisky', 
      'Grants', 
      'Grants whisky.', 
      290, 
      'https://loremflickr.com/400/300/grants%2Cwhisky', 
      4.5, 
      15, 
      true
    ),
(
      'black-white-2yzqt', 
      'regular-whisky', 
      'Black & White', 
      'Black & White whisky.', 
      290, 
      'https://loremflickr.com/400/300/black%2Cwhite%2Cwhisky', 
      4.5, 
      15, 
      true
    ),
(
      'bacardi-rum-4zonv', 
      'spirits', 
      'Bacardi Rum', 
      'Bacardi rum.', 
      310, 
      'https://loremflickr.com/400/300/bacardi%2Crum', 
      4.5, 
      15, 
      true
    ),
(
      'gordon-s-gin-hun88', 
      'spirits', 
      'Gordon''s Gin', 
      'Gordon''s gin.', 
      220, 
      'https://loremflickr.com/400/300/gordons%2Cgin', 
      4.5, 
      15, 
      true
    ),
(
      'extra-special-gin-qgkid', 
      'spirits', 
      'Extra Special Gin', 
      'Extra special gin.', 
      450, 
      'https://loremflickr.com/400/300/extra%2Cspecial%2Cgin', 
      4.5, 
      15, 
      true
    ),
(
      'stolichnaya-vodka-xdzc0', 
      'spirits', 
      'Stolichnaya Vodka', 
      'Stolichnaya vodka.', 
      310, 
      'https://loremflickr.com/400/300/stolichnaya%2Cvodka', 
      4.5, 
      15, 
      true
    ),
(
      'extra-special-vodka-hf899', 
      'spirits', 
      'Extra Special Vodka', 
      'Extra special vodka.', 
      450, 
      'https://loremflickr.com/400/300/extra%2Cspecial%2Cvodka', 
      4.5, 
      15, 
      true
    ),
(
      'tequila-exs4a', 
      'spirits', 
      'Tequila', 
      'Tequila.', 
      408, 
      'https://loremflickr.com/400/300/tequila', 
      4.5, 
      15, 
      true
    );

